In [30]:
import numpy as np


In [31]:
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)
print(arr.shape)
len(arr)


[10 20 30 40 50]
1
(5,)


5

In [32]:
arr_2d = np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400, 500]
])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(len(arr_2d))
print(arr_2d.size)
type(arr_2d)
arr_2d.dtype


[[ 10  20  30  40  50]
 [100 200 300 400 500]]
2
(2, 5)
2
10


dtype('int64')

In [33]:
np.full(shape = (3,5), fill_value = 'cat')
np.arange(start=1, stop=5, step=1)
np.arange(4)


array([0, 1, 2, 3])

In [34]:
foo = np.array([10, 20, 30, 40, 50])
foo[0]  # 10, 1st element
foo[1]  # 20, 2nd element
foo[1] = 99
print(foo[-1])


50


In [35]:
bar = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60]
])

In [36]:
zoo = np.array([
    [
        [10,20],
        [30,40],
        [50,60],
    ],
    [
        [11,12],
        [13,14],
        [15,16],
    ]
])


In [37]:
foo = np.array([[4,3], [1,0]])
bar = np.array([[1,2], [3,4]])

In [38]:
foo + bar
foo-bar 
foo * bar
foo / bar


array([[4.        , 1.5       ],
       [0.33333333, 0.        ]])

In [39]:
foo @ bar
foo + 5


array([[9, 8],
       [6, 5]])

In [40]:

dailywts = 185 - np.arange(5*7)/5
sat = dailywts[5::7]
sun = dailywts[6::7]
sum = sat + sun
avg = sum/2
print(avg)

[183.9 182.5 181.1 179.7 178.3]


In [45]:
#NOLA Problem

nola = np.arange(start=1, stop=65, step=2).reshape(4,-1)nola = nola[:, :-1]
print(nola)


ValueError: cannot reshape array of size 31 into shape (4,newaxis)